find_package(Doxygen REQUIRED)

set(TIMERTT_DOXYGEN_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
set(TIMERTT_DOXYGEN_INPUT
	"${PROJECT_SOURCE_DIR}/include/timertt ${CMAKE_CURRENT_SOURCE_DIR}/dox")
set(TIMERTT_DOXYGEN_EXAMPLE_PATH
	"${PROJECT_SOURCE_DIR}/samples ${PROJECT_SOURCE_DIR}")
set(TIMERTT_DOXYGEN_WARN_LOGFILE
	"${CMAKE_CURRENT_BINARY_DIR}/warnings.log")

configure_file(
	${CMAKE_CURRENT_SOURCE_DIR}/Doxyfile.in
	${CMAKE_CURRENT_BINARY_DIR}/Doxyfile
	@ONLY)

add_custom_target(timertt_docs
	COMMAND ${DOXYGEN_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile
	WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
	COMMENT "Building timertt API documentation")

